language: java

jdk: oraclejdk8

addons:
  sonarqube: true
  
env:
  global:
  - secure: EtA65cmMeiEHCQrWqr/0ItTvPH8/lw3vkgQVHfIN7ohF7eeUNIF/WDQDFB5Am3M3QBlUOLTG5i+5AYzoKqk2ZW2nLRLee8L3rJpht7316AgWcq9joLZmuhiiOSOuwfaSCKPzHjUW31EkZ0oGirzaxxaUzutLD5WBcHkKB2YvdTf6uHK7dJCEooPwTyDSiFyPUm0GA+U/zaCto6MocPvI1MIC/xXY6zSgRPLx+wK3YzHAG/rpVhFwdugwiLmZz2L1lNYl27AJR/GYKni2HBZCQqQmqJ3+LlbKVyr34RyQukBrpzpYxUINd+Dwl/1CHweeXQ11woi7KZQb9zzjIldXYdcut4qfgmOIhuKxvKQXiCVrf3Owps+KxHgnPsd3+ALhscmAW4wwS+Be510VHmHMsdn5v8UhbiLL3pv4a9sSoGvSctLmZDVOYz839TRz/8jocznQsO99vCviYqDXeYu7DIMOJrOY3spLAKnTz+F0hNeyd/uL318oIrty5PzbXHTMm/xcQZih5ZEzQRmEWCPkVsNdxDyGjXCcaGUB8PQzMPZ9iYeQGkX8380985D/Kf/P0OC+hpajwmdJPJPQPVbONoz8w3LIn0B7uteP/W4mawbNd2eFOJPhFq8FcDYwRiCxWx1Gg8darUVLXBGmgn4VEgiCiPDNz+B7xzJ3nKo8lQY=
  - secure: pQtQIg2rZGba1coMEfdCt50PtIw6I4JDmeIbl9v9l9vfnbhUUQPlPvBscaTQWvZWQVABG8d917p4kTnAiigzxxgKhDcNxOG5fLn69aGg6AcV9/5CyWISsK8TmgNqoHR8f52YjB3P8zbGlITVFkTITK/NyRFd3XFzi0B6hVY00URZeCwMauzmuvMm5sw6tK+aJEn1xaPahWFD711RlO8EimKq2tPw9ZBQ848U3FjrYpl/7bPlEaHANTRzHj52gLzcrZSXUu9D2JACIxu7IB20Lvy/p6SYYUNBeVgEGFQWvdnQALo1jcOgktFe6j/i7J1D7Vf/qqouZXPCUXHKQgGQP70IaLHCJPDI8TUPxYnPabTdbSNUZgrsUdHd0bn+hCPLoxVVEEz70wzVhOVZfjb28AhqOv0g+ke4JySj6X8NnCydPM98TJiJizxrhSc5qKJqJntPY4pcavNB9Z6jkX7qAeUROPQ0oSSfLxqYJ7+RAeqX7otJBTaP3spyd8tZYp18CJwbov3F4pIg/KbYDHHGamGf6GNcmQ2JVvHIr2hmWwES+krDjr43nCGUmC+rIm8JN5Yk5mpB3qRiIsQM3TqRNNOx7TV31vldCsu6tXF1PdBdltR+QxBbgLz2EotKW5Ky38YlHVPDEzS2G8ysPMgQRlINXcdpUlGTZ04/M6gtEWY=

install: mvn install --settings .travis/settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V 

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      mvn site --settings .travis/settings.xml;
    fi
